version: "3.7"

services:

  database:
    build: docker/data
    container_name: ${API}-database
    working_dir: /mnt/api
    volumes:
      - ./docker/mysql:/var/lib/mysql
    user: mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "33306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"

  node:
    build: docker/nodejs
    working_dir: /mnt/api
    container_name: ${API}-node
    volumes:
      - "./api:/mnt/api"
    ports:
      - "4002:4000"
      - "56745:56745"
