version: "3.7"

services:
  nodejs:
    build: docker/nodejs
    working_dir: /mnt/api
    container_name: ${APP}-node
    volumes:
      - ".:/mnt/api"
    ports:
      - "4003:4000"

  redis:
    image: redis:alpine
    container_name: ${APP}-redis

  adminredis:
    image: erikdubbelboer/phpredisadmin
    container_name: ${APP}-admin-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=MyRedis
    ports:
      - "8091:80"
